linux_docker_builder:
  script: docker build -t $CIRRUS_REPO_FULL_NAME:latest-amd64 . -f Dockerfile

publish_docker_builder:
  depends_on: 
    - linux
    - windows
  env:
    DOCKERHUB_USER: ENCRYPTED[bea6c673c5d29047e9ac193e0acf65d21f213a25021438e72b12471f3eabb991fe68f288059cae920e5d9449cf8400cf]
    DOCKERHUB_PASS: ENCRYPTED[53cfe08d15ffdb89b477ceebf39fcd05f34a99edc60f7a494ebb2f4e99e9410457ada52a8c03cd6fab32df6d1f31e51d]
  script: | 
    mkdir $HOME/.docker
    sh -c 'echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json'
    docker info
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:cirrus-linux
    docker manifest create $CIRRUS_REPO_FULL_NAME:latest $CIRRUS_REPO_FULL_NAME:latest-amd64
    docker manifest push $CIRRUS_REPO_FULL_NAME:latest -p

