linux_docker_builder:
  script: docker build -t $CIRRUS_REPO_FULL_NAME:latest-amd64 . -f Dockerfile

publish_docker_builder:
  depends_on: 
    - linux
    - windows
  env:
    DOCKERHUB_USER: ENCRYPTED[98e575fd2885ba39b429cdcd5c7bbfad8db12e0c4f391f0f58fea9952bf41c2d25a7567b52dc17bfff1faa810921f6de]
    DOCKERHUB_PASS: ENCRYPTED[2266391061fded5e8db8300e5a53276e4081eb8bdd73caf665e48c19ef3a8946b7bd7188f011ca588c3b9cdfd840e0fd]
  script: | 
    mkdir $HOME/.docker
    sh -c 'echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json'
    docker info
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:cirrus-linux
    docker manifest create $CIRRUS_REPO_FULL_NAME:latest $CIRRUS_REPO_FULL_NAME:latest-amd64
    docker manifest push $CIRRUS_REPO_FULL_NAME:latest -p

